---
# yamllint disable rule:line-length
###############################################################################
# Assert Settings
###############################################################################
# Sanity check options to stop preventable errors and accidental data deletion.

- name: 'Assert | email notification requirements'
  when: seerr_cfg_agents_email_enabled
  ansible.builtin.assert:
    quiet: true
    that:
      - seerr_cfg_agents_email_email_from | length > 0
      - seerr_cfg_agents_email_smtp_host | length > 0
      - seerr_cfg_agents_email_smtp_port is defined
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │           Email notifications require all options set.            │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_agents_email_enabled: '{{ seerr_cfg_agents_email_enabled }}'
      │ seerr_cfg_agents_email_email_from: '{{ seerr_cfg_agents_email_email_from }}'
      │ seerr_cfg_agents_email_smtp_host: '{{ seerr_cfg_agents_email_smtp_host }}'
      │ seerr_cfg_agents_email_smtp_port: '{{ seerr_cfg_agents_email_smtp_port }}'
      │ seerr_cfg_agents_email_secure: '{{ seerr_cfg_agents_email_secure }}'
      │ seerr_cfg_agents_email_ignore_tls: '{{ seerr_cfg_agents_email_ignore_tls }}'
      │ seerr_cfg_agents_email_require_tls: '{{ seerr_cfg_agents_email_require_tls }}'

- name: 'Assert | discord notification requirements'
  when: seerr_cfg_agents_discord_enabled
  ansible.builtin.assert:
    quiet: true
    that: seerr_cfg_agents_discord_webhook_url | length > 0
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │          Discord notifications require all options set.           │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_agents_discord_enabled: '{{ seerr_cfg_agents_discord_enabled }}'
      │ seerr_cfg_agents_discord_webhook_url: '{{ seerr_cfg_agents_discord_webhook_url }}'

- name: 'Assert | gotify notification requirements'
  when: seerr_cfg_agents_gotify_enabled
  ansible.builtin.assert:
    quiet: true
    that:
      - seerr_cfg_agents_gotify_url | length > 0
      - seerr_cfg_agents_gotify_token | length > 0
      - seerr_cfg_agents_gotify_priority is defined
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │           Gotify notifications require all options set.           │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_agents_gotify_enabled: '{{ seerr_cfg_agents_gotify_enabled }}'
      │ seerr_cfg_agents_gotify_url: '{{ seerr_cfg_agents_gotify_url }}'
      │ seerr_cfg_agents_gotify_token: '{{ seerr_cfg_agents_gotify_token }}'
      │ seerr_cfg_agents_gotify_priority: '{{ seerr_cfg_agents_gotify_priority }}'

- name: 'Assert | ntfy.sh notification requirements'
  when: seerr_cfg_agents_ntfy_enabled
  ansible.builtin.assert:
    quiet: true
    that:
      - seerr_cfg_agents_ntfy_url | length > 0
      - seerr_cfg_agents_ntfy_topic | length > 0
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │          notfy.sh notifications require all options set.          │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_agents_ntfy_enabled: '{{ seerr_cfg_agents_gotify_enabled }}'
      │ seerr_cfg_agents_ntfy_url: '{{ seerr_cfg_agents_gotify_url }}'
      │ seerr_cfg_agents_ntfy_topic: '{{ seerr_cfg_agents_gotify_token }}'

- name: 'Assert | ntfy.sh user password requirements'
  when: seerr_cfg_agents_ntfy_auth_method_username_password
  ansible.builtin.assert:
    quiet: true
    that:
      - seerr_cfg_agents_ntfy_username | length > 0
      - seerr_cfg_agents_ntfy_password | length > 0
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │         notfy.sh password auth requires all options set.          │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_agents_ntfy_auth_method_username_password: '{{ seerr_cfg_agents_ntfy_auth_method_username_password }}'
      │ seerr_cfg_agents_ntfy_username: '{{ seerr_cfg_agents_ntfy_username }}'
      │ seerr_cfg_agents_ntfy_password: '{{ seerr_cfg_agents_ntfy_password }}'

- name: 'Assert | ntfy.sh token requirements'
  when: seerr_cfg_agents_ntfy_auth_method_token
  ansible.builtin.assert:
    quiet: true
    that: seerr_cfg_agents_ntfy_token | length > 0
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │           notfy.sh token auth requires all options set.           │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_agents_ntfy_auth_method_token: '{{ seerr_cfg_agents_ntfy_auth_method_token }}'
      │ seerr_cfg_agents_ntfy_token: '{{ seerr_cfg_agents_ntfy_token }}'

- name: 'Assert | pushbullet notification requirements'
  when: seerr_cfg_agents_pushbullet_enabled
  ansible.builtin.assert:
    quiet: true
    that: seerr_cfg_agents_pushbullet_access_token | length > 0
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │         Pushbullet notifications require all options set.         │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_agents_pushbullet_enabled: '{{ seerr_cfg_agents_pushbullet_enabled }}'
      │ seerr_cfg_agents_pushbullet_access_token: '{{ seerr_cfg_agents_pushbullet_access_token }}'

- name: 'Assert | pushover notification requirements'
  when: seerr_cfg_agents_pushover_enabled
  ansible.builtin.assert:
    quiet: true
    that:
      - seerr_cfg_agents_pushover_access_token | length > 0
      - seerr_cfg_agents_pushover_user_token | length > 0
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │          Pushover notifications require all options set.          │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_agents_pushover_enabled: '{{ seerr_cfg_agents_pushover_enabled }}'
      │ seerr_cfg_agents_pushover_access_token: '{{ seerr_cfg_agents_pushover_access_token }}'
      │ seerr_cfg_agents_pushover_user_token: '{{ seerr_cfg_agents_pushover_user_token }}'

- name: 'Assert | slack notification requirements'
  when: seerr_cfg_agents_slack_enabled
  ansible.builtin.assert:
    quiet: true
    that: seerr_cfg_agents_slack_webhook_url | length > 0
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │           Slack notifications require all options set.            │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_agents_slack_enabled: '{{ seerr_cfg_agents_slack_enabled }}'
      │ seerr_cfg_agents_slack_webhook_url: '{{ seerr_cfg_agents_slack_webhook_url }}'

- name: 'Assert | telegram notification requirements'
  when: seerr_cfg_agents_telegram_enabled
  ansible.builtin.assert:
    quiet: true
    that:
      - seerr_cfg_agents_telegram_bot_api | length > 0
      - seerr_cfg_agents_telegram_chat_id | length > 0
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │          Telegram notifications require all options set.          │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_agents_telegram_enabled: '{{ seerr_cfg_agents_telegram_enabled }}'
      │ seerr_cfg_agents_telegram_bot_api: '{{ seerr_cfg_agents_telegram_bot_api }}'
      │ seerr_cfg_agents_telegram_chat_id: '{{ seerr_cfg_agents_telegram_chat_id }}'

- name: 'Assert | web push requires HTTPS'
  when: seerr_cfg_agents_webpush_enabled
  ansible.builtin.assert:
    quiet: true
    that:
      - seerr_cfg_trust_proxy or seerr_cfg_proxy_enabled
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │          Web Push notifications require all options set.          │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_agents_webpush_enabled: '{{ seerr_cfg_agents_webpush_enabled }}'
      │ seerr_cfg_trust_proxy: '{{ seerr_cfg_trust_proxy }}'
      │ seerr_cfg_proxy_enabled: '{{ seerr_cfg_proxy_enabled }}'

      See: https://docs.seerr.dev/using-seerr/notifications/webpush

- name: 'Assert | webhook notification requirements'
  when: seerr_cfg_agents_webhook_enabled
  ansible.builtin.assert:
    quiet: true
    that:
      - seerr_cfg_agents_webhook_webhook_url | length > 0
      - seerr_cfg_agents_webhook_json_payload | length > 0
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │          Webhook notifications require all options set.           │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_agents_webhook_enabled: '{{ seerr_cfg_agents_webhook_enabled }}'
      │ seerr_cfg_agents_webhook_webhook_url: '{{ seerr_cfg_agents_webhook_webhook_url }}'
      │ seerr_cfg_agents_webhook_json_payload: '{{ seerr_cfg_agents_webhook_json_payload }}'

- name: 'Assert | owner defined'
  ansible.builtin.assert:
    quiet: true
    that:
      - seerr_srv_owner_email | length > 0
      - seerr_srv_owner_username | length > 0
      - seerr_srv_owner_password | length > 0
      - seerr_srv_owner_avatar | length > 0
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │                      Owner must be defined.                       │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_srv_owner_email: '{{ seerr_srv_owner_email }}'
      │ seerr_srv_owner_username: '{{ seerr_srv_owner_username }}'
      │ seerr_srv_owner_password: '{{ seerr_srv_owner_password }}'
      │ seerr_srv_owner_avatar: '{{ seerr_srv_owner_avatar }}'

- name: 'Assert | postgres server options mutually exclusive'
  when: seerr_cfg_db_type != 'sqlite'
  ansible.builtin.assert:
    quiet: true
    that: seerr_cfg_db_host != seerr_cfg_db_socket_path
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │          Postgres server options are mutually exclusive.          │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ seerr_cfg_db_host: '{{ seerr_cfg_db_host }}'
      │ seerr_cfg_db_socket_path: '{{ seerr_cfg_db_socket_path }}'
