---
###############################################################################
# Seerr YARN Configuration
###############################################################################
# Limit V8 object cache to system memory size and disable source maps. If
# javascript heap out of memory error continually occurs increase the minimum
# memory requirement for the role.
#
# Reference:
# * https://docs.seerr.dev/getting-started/buildfromsource

- name: 'Build | Seerr from source 🗘'
  ansible.builtin.debug:
    msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │     Building Seerr from source. This will take a few minutes.     │
      │                                                                   │
      ╰───────────────────────────────────────────────────────────────────╯

- name: 'Build | compile {{ _seerr_srv_version.raw }}'
  ansible.builtin.shell: >
    source {{ _seerr.nvm_env }} &&
    corepack use pnpm@latest-{{ seerr__nvm_pnpm_version }} &&
    pnpm build
  args:
    executable: '/bin/bash'
    chdir: '{{ seerr_role_opt_dir }}'
  environment:
    NODE_OPTIONS: '{{
        _seerr_srv_build_memory._args ~
        _seerr_srv_build_memory.data
      }}'
    GENERATE_SOURCEMAP: 'false'
  changed_when: false
  become: true
  become_user: '{{ _seerr_srv_user.raw }}'

- name: 'Build | clear cache'
  when: _seerr_srv_build_clear_cache.raw
  ansible.builtin.shell: >
    source {{ _seerr.nvm_env }} &&
    corepack use pnpm@latest-{{ seerr__nvm_pnpm_version }} &&
    pnpm store prune
  args:
    executable: '/bin/bash'
    chdir: '{{ seerr_role_opt_dir }}'
  changed_when: false
  become: true
  become_user: '{{ _seerr_srv_user.raw }}'
