---
###############################################################################
#  Pre Execution Tasks
###############################################################################
# Only use data annotations in role after merging role, defaults, runtime data.
# Service may not exist if first install.
#
# Reference:
# * https://seerr.dev/
# * https://github.com/sct/seerr/
# * https://docs.seerr.dev/getting-started/installation

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    seerr__srv: "{{ seerr___release | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),
        _token=seerr_srv_token,
        _user=seerr_srv_user,
        _group=seerr_srv_group,
      ) }}"
    seerr__cfg: "{{ {} | r_pufky.data.v3(

        _version=seerr_srv_version,
        _package=seerr_srv_version ~ '.tar.gz',
        _d=seerr_cfg_d | regex_replace('\\/$', ''),
        _backup_d=seerr_cfg_backup_d | regex_replace('\\/$', ''),
        _backup_metadata=seerr_cfg_backup_metadata,
        _app_d='/opt/seerr/src/' ~ seerr_srv_version,
        _package_json='/opt/seerr/src/' ~ seerr_srv_version ~ '/package.json',
        _url=seerr___repo_url ~ seerr___release._app ~ '.tar.gz',
      ) }}"

- name: 'Prep | assert | backup enabled and location defined'
  when: seerr_flg_backup
  ansible.builtin.assert:
    quiet: true
    that:
      - seerr__cfg._backup_d | length > 0
    fail_msg: |

      ✘ Backup location not set.
      Backups enabled but no backup location defined.

      seerr_flg_backup: {{ seerr_flg_backup }}
      seerr_cfg_backup_d: {{ seerr__cfg._backup_d }}

- name: 'Prep | assert | restore enabled and location defined'
  when: seerr_flg_restore
  ansible.builtin.assert:
    quiet: true
    that:
      - seerr__cfg._backup_d | length > 0
    fail_msg: |

      ✘ Backup location not set.
      Backups enabled but no backup location defined.

      seerr_flg_restore: {{ seerr_flg_restore }}
      seerr_cfg_backup_d: {{ seerr__cfg._backup_d }}

- name: 'Prep | assert | config enabled and source defined'
  when: seerr_flg_config
  ansible.builtin.assert:
    quiet: true
    that:
      - seerr__cfg._d | length > 0
    fail_msg: |

      ✘ Config source not set.
      Config source enabled but no config source defined.

      seerr_flg_config: {{ seerr_flg_config }}
      seerr_cfg_d: {{ seerr__cfg._d }}

- name: '{{ "Prep | account | query user " ~ seerr__srv._user }}'
  ansible.builtin.command: '{{ "id " ~ seerr__srv._user }}'
  failed_when: false
  register: seerr__cfg_check
  changed_when: seerr__cfg_check.rc > 0

- name: '{{ "Prep | account | query group " ~ seerr__srv._group }}'
  ansible.builtin.command: '{{ "groups " ~ seerr__srv._group }}'
  failed_when: false
  register: seerr__group_check
  changed_when: seerr__group_check.rc > 0

- name: '{{ "Prep | account | create group " ~ seerr__srv._group }}'
  when: seerr__group_check.rc != 0
  ansible.builtin.group:
    gid: '{{ seerr___group.gid }}'
    name: '{{ seerr___group.name }}'
    state: 'present'

- name: '{{ "Prep | account | create user " ~ seerr__srv._user }}'
  when: seerr__cfg_check.rc != 0
  ansible.builtin.user:
    name: '{{ seerr___user.name }}'
    group: '{{ seerr___user.group }}'
    uid: '{{ seerr___user.uid }}'
    shell: '{{ seerr___user.shell }}'
    home: '{{ seerr___user.home }}'
    create_home: '{{ seerr___user.create_home }}'
    password: '{{ seerr___user.password }}'
    password_lock: '{{ seerr___user.password_lock }}'
    update_password: '{{ seerr___user.update_password }}'
    expires: '{{ seerr___user.expires }}'
    system: '{{ seerr___user.system }}'

# Pre-existing users may have a different UID/GID/Home.
- name: '{{ "Prep | account | enumerate " ~ seerr__srv._user }}'
  ansible.builtin.user:
    name: '{{ seerr__srv._user }}'
  check_mode: true
  changed_when: false
  register: seerr__cfg_query

- name: 'Prep | fact | parse service UID/GID'
  ansible.builtin.set_fact:
    seerr__cfg: "{{ seerr__cfg | r_pufky.data.v3(

        _uid=seerr__cfg_query.uid,
        _gid=seerr__cfg_query.group,
        _home=seerr__cfg_query.home,
      ) }}"

- name: 'Prep | systemd | stop seerr.service'
  ansible.builtin.systemd:
    name: 'seerr.service'
    state: 'stopped'
  failed_when: false
