---
###############################################################################
# Validate
###############################################################################
# Ensure Seerr services and confirm they are active and running.
#
# Service already started to update local users.

- name: 'Validate | query service status'
  ansible.builtin.service_facts:

- name: 'Validate | assert services running'
  ansible.builtin.assert:
    quiet: true
    that: ansible_facts.services[item].state == 'running'
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │                     Service failed to start.                      │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ {{ item }}
  loop:
    - 'seerr.service'
