---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | create cache'

    - name: 'Prepare | parse test version'
      ansible.builtin.set_fact:
        test_version: '2.7.3'

    - name: '{{ "Prepare | cache " ~ test_version }}'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: '{{ "Prepare | cache " ~ test_version }}'
        test_dest: '{{ "v" ~ test_version ~ ".tar.gz" }}'
        test_url: '{{
            "https://github.com/seerr-team/seerr/archive/refs/tags/" ~
            "v" ~ test_version ~ ".tar.gz"
          }}'
        test_mode: '0640'
