---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: '{{ "Verify | test | " ~ seerr___app._env }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name: '{{ "Verify | test | " ~ seerr___app._env }}'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/templates/default/.env"
          }}'
        test_file: '{{ seerr___app._env }}'
        test_owner: 'seerr'
        test_group: 'seerr'
        test_mode: '0640'
        test_diff: true
