---
###############################################################################
# Settings > Notifications > Discord (settings.json > discord)
###############################################################################
# Reference:
# * https://docs.seerr.dev/using-seerr/notifications/discord

# Enable notifications? Default: False.
seerr_cfg_agents_discord_enabled: false

# Webhook URL. Default: ''.
#
# Discord URL location: Server Settings > Integrations > Webhooks.
#
# Reference:
# * https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
seerr_cfg_agents_discord_webhook_url: ''

# Bot username. Default: ''.
seerr_cfg_agents_discord_bot_username: ''

# Bot avatar URL. Default: ''.
seerr_cfg_agents_discord_bot_avatar_url: ''

# Webhook notification role ID. Default: ''.
seerr_cfg_agents_discord_webhook_role_id: ''

# Enable user mentions in discord? Default: True.
seerr_cfg_agents_discord_enable_mentions: true

# Allowed notification types.
#
# Values are added cumulatively together to specify exact notifications.
#
# Values:
#      0: Notifications disabled.
#      2: Request pending approval (users submit new media requests which
#         require approval).
#      4: Request approved (media requests are manually approved).
#      8: Request available (media requests become available).
#     16: Request processing failed (media requests fail to be added to Radarr
#         or Sonarr).
#     64: Request declined (media requests are declined).
#    128: Request automatically approved (users submit new media requests which
#         are automatically approved).
#    256: Issue reported (issues are reported).
#    512: Issue comment (issues receive new comments).
#   1024: Issue resolved (issues are resolved).
#   2048: Issue reopened (issues are reopened).
#
# Allow 'request pending approval', 'request declined', 'issue reported':
#   seerr_cfg_agents_discord_types: 322
#
# Default: 0.
seerr_cfg_agents_discord_types: 0
