---
###############################################################################
# Settings > Notifications > Gotify (settings.json > gotify)
###############################################################################
# Reference:
# * https://gotify.net/docs/

# Enable notifications? Default: False.
seerr_cfg_agents_gotify_enabled: false

# Server URL. Default: ''.
seerr_cfg_agents_gotify_url: ''

# Application token. Default: ''.
seerr_cfg_agents_gotify_token: ''

# Notification priority.
#
# Values:
#    0: Test message (lowest).
#    1: Lowest message priority.
#   10: Highest message priority.
#
# Default: 0 (test message).
seerr_cfg_agents_gotify_priority: 0

# Allowed notification types.
#
# Values are added cumulatively together to specify exact notifications.
#
# Values:
#      0: Notifications disabled.
#      2: Request pending approval (users submit new media requests which
#         require approval).
#      4: Request approved (media requests are manually approved).
#      8: Request available (media requests become available).
#     16: Request processing failed (media requests fail to be added to Radarr
#         or Sonarr).
#     64: Request declined (media requests are declined).
#    128: Request automatically approved (users submit new media requests which
#         are automatically approved).
#    256: Issue reported (issues are reported).
#    512: Issue comment (issues receive new comments).
#   1024: Issue resolved (issues are resolved).
#   2048: Issue reopened (issues are reopened).
#
# Allow 'request pending approval', 'request declined', 'issue reported':
# seerr_cfg_agents_gotify_types: 322
#
# Default: 0.
seerr_cfg_agents_gotify_types: 0
