---
###############################################################################
# Settings > Notifications > ntfy.sh (settings.json > ntfy)
###############################################################################
# Reference:
# * https://docs.ntfy.sh/

# Enable notifications? Default: False.
seerr_cfg_agents_ntfy_enabled: false

# Server root URL. Default: ''.
seerr_cfg_agents_ntfy_url: ''

# Topic. Default: ''.
seerr_cfg_agents_ntfy_topic: ''

# Use username/password authentication?
#
# Requires:
#   seerr_cfg_agents_ntfy_username, seerr_cfg_agents_ntfy_password.
#
# Disables token authentication.
#
# Default: False.
seerr_cfg_agents_ntfy_auth_method_username_password: false

# Username.
#
# Requires: seerr_cfg_agents_ntfy_auth_method_username_password.
#
# Default: ''.
seerr_cfg_agents_ntfy_username: ''

# Password.
#
# Requires: seerr_cfg_agents_ntfy_auth_method_username_password.
#
# Default: ''.
seerr_cfg_agents_ntfy_password: ''

# Use token authentication?
#
# Requires: seerr_cfg_agents_ntfy_token.
#
# Disables username/password authentication.
#
# Default: False.
seerr_cfg_agents_ntfy_auth_method_token: false

# Username.
#
# Requires: seerr_cfg_agents_ntfy_auth_method_token.
#
# Default: ''.
seerr_cfg_agents_ntfy_token: ''

# ntfy allowed notification types.
#
# Values are added cumulatively together to specify exact notifications.
#
# Values:
#      0: Notifications disabled.
#      2: Request pending approval (users submit new media requests which
#         require approval).
#      4: Request approved (media requests are manually approved).
#      8: Request available (media requests become available).
#     16: Request processing failed (media requests fail to be added to Radarr
#         or Sonarr).
#     64: Request declined (media requests are declined).
#    128: Request automatically approved (users submit new media requests which
#         are automatically approved).
#    256: Issue reported (issues are reported).
#    512: Issue comment (issues receive new comments).
#   1024: Issue resolved (issues are resolved).
#   2048: Issue reopened (issues are reopened).
#
# Allow 'request pending approval', 'request declined', 'issue reported':
# seerr_cfg_agents_gotify_types: 322
#
# Default: 0.
seerr_cfg_agents_ntfy_types: 0
