---
###############################################################################
# Settings > Notifications > Webpush (settings.json > webpush)
###############################################################################
# The web push notification agent enables you and your users to receive
# Seerr notifications in a supported browser.
#
# Requires: seerr_cfg_trust_proxy=true|seerr_cfg_proxy_enabled=true.
#
# This notification agent does not require any configuration, but is not
# enabled in Seerr by default.
#
# The web push agent only works via HTTPS. Refer to our reverse proxy examples
# for help on proxy Seerr traffic via HTTPS.
#
# Reference:
# * https://docs.seerr.dev/using-seerr/notifications/webpush
seerr_cfg_agents_webpush_enabled: false
